name: android-adb
version: 5.1
summary: Android tool adb
description: |
  Android adb tool, used to manage android's bootloader

grade: stable
confinement: devmode

parts:
  android-tools:
    source: https://github.com/ubports/android-tools.git
    plugin: make
    build-packages:
      - libssl-dev
      - libselinux-dev
      - zlib1g-dev
      - gcc
apps:
  android-adb:
    command: adb
    plugs:
      - network-bind
      - raw-usb
#      - adb-support
